# Generated by Django 5.0 on 2024-02-19 12:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='packing_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='information',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
