# Generated by Django 5.0 on 2024-02-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contact_us_alter_filter_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
