# Generated by Django 5.0 on 2024-02-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_contact_us_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
